export const board = [
    { "name": "Go", "number": 0, "set": null },
    { "name": "Mediterranean Avenue", "number": 1, "set": "purple" },
    { "name": "Community Chest", "number": 2, "set": null },
    { "name": "Baltic Avenue", "number": 3, "set": "purple" },
    { "name": "Income Tax", "number": 4, "set": null },
    { "name": "Reading Railroad", "number": 5, "set": "railroads" },
    { "name": "Oriental Avenue", "number": 6, "set": "light-blue" },
    { "name": "Chance", "number": 7, "set": null },
    { "name": "Vermont Avenue", "number": 8, "set": "light-blue" },
    { "name": "Connecticut Avenue", "number": 9, "set": "light-blue" },
    { "name": "Jail / Just Visiting", "number": 10, "set": null },
    { "name": "St. Charles Place", "number": 11, "set": "pink" },
    { "name": "Electric Company", "number": 12, "set": "utilities" },
    { "name": "States Avenue", "number": 13, "set": "pink" },
    { "name": "Virginia Avenue", "number": 14, "set": "pink" },
    { "name": "Pennsylvania Railroad", "number": 15, "set": "railroads" },
    { "name": "St. James Place", "number": 16, "set": "orange" },
    { "name": "Community Chest", "number": 17, "set": null },
    { "name": "Tennessee Avenue", "number": 18, "set": "orange" },
    { "name": "New York Avenue", "number": 19, "set": "orange" },
    { "name": "Free Parking", "number": 20, "set": null },
    { "name": "Kentucky Avenue", "number": 21, "set": "red" },
    { "name": "Chance", "number": 22, "set": null },
    { "name": "Indiana Avenue", "number": 23, "set": "red" },
    { "name": "Illinois Avenue", "number": 24, "set": "red" },
    { "name": "B. & O. Railroad", "number": 25, "set": "railroads" },
    { "name": "Atlantic Avenue", "number": 26, "set": "yellow" },
    { "name": "Ventnor Avenue", "number": 27, "set": "yellow" },
    { "name": "Water Works", "number": 28, "set": "utilities" },
    { "name": "Marvin Gardens", "number": 29, "set": "yellow" },
    { "name": "Go to Jail", "number": 30, "set": null },
    { "name": "Pacific Avenue", "number": 31, "set": "green" },
    { "name": "North Carolina Avenue", "number": 32, "set": "green" },
    { "name": "Community Chest", "number": 33, "set": null },
    { "name": "Pennsylvania Avenue", "number": 34, "set": "green" },
    { "name": "Short Line Railroad", "number": 35, "set": "railroads" },
    { "name": "Chance", "number": 36, "set": null },
    { "name": "Park Place", "number": 37, "set": "dark-blue" },
    { "name": "Luxury Tax", "number": 38, "set": null },
    { "name": "Boardwalk", "number": 39, "set": "dark-blue" }
]
