mazuStrings.de = {
    "mazu": {
        "fishName": "Fisch",
        "mazuName": "Mazu",
        "language": "Deutsch",
        "flags": "🇩🇪, 🇦🇹, 🇨🇭",
        "currencySymbol" : "€",

        "staticStrings": {
            "automateCatchLabel": "Automatisieren? ",
            "playerNameLabelText": "Wie ist dein Name? ",
            "fishQuantityLabelText": "Wie viele Fische? ",
            "gameCodeTextFieldLabelText": "Spielcode: ",
            "joinGameButton": "Mach mit",
            "catchButton": "Fangen",
            "setNameButton": "Dein Name",
            "loginButton": "anmelden",
            "logoutButton": "abmelden",
            "tagline": "Meeresgöttin",
            "startNewGameButton": "Einem neuen Spiel beitreten"
        },
        "attributeNames": {
            "year": "Jahr",
            "pop": "Fischpop",
            "seen": "gesehen",
            "want": "wollen",
            "caught": "gefangen",
            "before": "davor",
            "expenses": "Ausgaben",
            "unitPrice": "Einheitspreis",
            "income": "Einkunft",
            "after": "danach",
            "player": "Spieler",
            "game": "Spiel",
            "result": "Ausgang",
            "level": "Stufe"
        },
        "attributeDescriptions": {
            "year": "Spieljahr",
            "pop": "Die echte Population am Anfang des Jahres",
            "seen": "Wie viel Fische hast Du gesehen",
            "want": "Wie viele Fische Du fangen  wolltest",
            "caught": "Wie viele Fische Du gefangen hast",
            "before": "Saldo vor dem Zug",
            "expenses": "Ausgaben in diesem Jahr",
            "unitPrice": "Einheitspreis",
            "income": "Einkommen aus dem Firschverkauf",
            "after": "Saldo nach dem Zug",
            "player": "Name des Spielers",
            "game": "Spielcode",
            "result": "Resultat",
            "level": "Schwierigkeitsniveau",
            "itemID": "itemID"
        },
        "mazuFrameTitle": "Mazu, Meeresgöttin",
        "fishFrameTitle": "Fischerspiel",
        "sAnd": "und",
        "mazuDatasetTitle": "Spielberichte",
        "mazuDatasetDescription": "Berichte aller Spielrunden",
        "fishDataSetTitle": "Fischerberichte",
        "fishDataSetDescription": "Berichte Deiner Erfahrung auf dem Boot",
        "fishHistoricalDataSetTitle": "historische Berichte",
        "fishHistoricalDataSetDescription": "Historische Berichte jedes einzelnen Bootes",
        "firstPlayer": "Du wirst der erste Spieler sein.",
        "playingSolo": "Du spielst solo",
        "oneOtherPlayer": "Es gibt einen anderen Spieler",
        "manyOtherPlayers": "Es gibt %@1 weitere Spieler",
        "noPlayersYet": "Noch keine Spieler!",
        "waitingForYou": "Wartend auf <strong>DICH</strong>",
        "andHowManyMore": " und %@1 mehr.",
        "waitingFor": "Wartend auf",
        "catchFishCommand": "Fange Fische!",
        "end": {
            "timeRanOut": "Das Spiel endet im Jahr %@1. <br> ",
            "endedEarly": "Das Spiel endete früh in %@1.<br>",
            "fiveFishResult": "🐟🐟🐟🐟🐟 Gut gemacht! Fünf von fünf Fischen! <br>Die gesamte Fischpopulation ist gesund --- und so groß, dass man viele Fische fangen kann, ohne die Fischpopulation zu verringern. Die Fischerei ist jetzt eine nachhaltige Nahrungsquelle.",
            "fourFishResult": "🐟🐟🐟🐟 Deine Bewertung ist nun vier Fische (von fünf). <br> Die Gesamtzahl der Fische hat stark zugenommen! Du  kannst jetzt mehr Fische fangen, ohne die Population zu verringern. Schaffst Du  es auf fünf Sterne?",
            "threeFishResult": "🐟🐟🐟 Deine Bewertung ist drei Fische (von fünf). <br>die Gesamtzahl der Fische hat zugenommen! Dein Fischereigeschäft läuft gut, aber es könnte besser sein.",
            "twoFishResult": "🐟🐟 Deine Bewertung ist zwei Fische (von fünf). <br>die Gesamtzahl der Fische ist zurückgegangen. Dein Fischereigeschäft hat überlebt, aber der Fischbestand ist nicht gesund.",
            "oneFishResult": "🐟 Deine Bewertung ist nur ein Fisch (von fünf). <br>die Gesamtzahl der Fische ist sehr gering. Du kannst möglicherweise nicht mehr lange fischen.",
            "zeroFishResult": "💀 Deine Bewertung ist null Fische (von fünf)! <br>Die Fische werden alle bald weg sein und die Fischereiindustrie ist zusammengebrochen.",
            "bankruptFishResult": "💀 Deine Bewertung ist null Fische (von fünf)! <br>Du hast das Spiel verloren, weil diese Spieler bankrott gegangen sind: %@1.",
            "meanBalanceResult" : "<br>Am Ende des Spiels betrug der durchschnittliche Kontostand %@1%@2"
        },
        "everyoneHasFished": "Jeder hat Fische gefangen.",
        "waitingForYouToLogIn": "Man wartet darauf, dass Du Dich einloggst.",
        "waitForFishSale": "Auf dem Fischmarkt hast du %@1 Fisch. <br> Warte  bis sie verkauft werden.",
        "noFishWaitForTurnEnd": "Du hast keine Fische auf dem Fischmarkt.  Warte <br> bis die Runde zuende ist. ",
        "seenFishReport": "Diese Jahr hast Du %@1 Fische gesehen. ",
        "caughtAllReport": "Du hast %@1 Fische gefangen, wie Du wolltest. ",
        "caughtSomeReport": "<br> Du wolltest %@1 Fische, hast Du aber nur %@2 gefangen. ",
        "recentTurnReport": "Deine letzte volle Runde war das Jahr %@1.<br>Du hast %@2 Fische gesehen, wolltest %@3 und hast %@4 gefangen.<br>Du hast sie für jeweils %@7%@5 verkauft, also insgesamt %@7%@6.",
        "buttons": {
            "leaveGameButton": "Spiel verlassen",
            "sellFishButton": "Fisch verkaufen",
            "newGameRadioLabel": "neues Spiel",
            "oldGameRadioLabel": "altes Spiel"
        },
        "admin": {
            "playerTableHeader": "<tr>\n                <th>Name</th>\n                <th>wollen</th>\n                <th>Saldo</th>\n                <th>Status</th>\n                <th>spielend</th>\n</tr>",
            "fishMarket": "Fischmarkt",
            "noGameYet": "Es gibt noch kein Spiel",
            "welcomeBack": "willkommen zurück",
            "welcomeToMazu": "Willkommen in Mazu",
            "youHaveRejoined": "Sie sind dem Spiel wieder beigetreten: ",
            "automateMarket": "automatisieren den Fischmarkt"
        },
        "timeTerms": {
            "second": "Sekunden",
            "minute": "Minuten",
            "hour": "Stunden",
            "day": "Tage",
            "month": "Monate"
        }
    }
}