mazuStrings.it = {
    "mazu": {
        "fishName": "pesce",
        "mazuName": "mazu",
        "language": "Italiano",
        "flags": "🇮🇹",
        "staticStrings": {
            "automateCatchLabel": "automatizzare? ",
            "playerNameLabelText": "come ti chiami? ",
            "fishQuantityLabelText": "Quanti pesci? ",
            "gameCodeTextFieldLabelText": "codice del gioco: ",
            "joinGameButton": "partecipa\n",
            "catchButton": "pesca",
            "setNameButton": "Scrivi il tuo nome",
            "loginButton": "login",
            "logoutButton": "disconnettersi",
            "tagline": "dea del mare",
            "startNewGameButton": "OK, partecipa a un nuovo gioco"
        },
        "attributeNames": {
            "year": "anno",
            "pop": "pop",
            "seen": "visto",
            "want": "Volere",
            "caught": "preso",
            "before": "Prima",
            "expenses": "spese",
            "unitPrice": "prezzo unitario",
            "income": "reddito",
            "after": "Dopo",
            "player": "giocatore",
            "game": "gioco",
            "result": "risultato",
            "level": "livello"
        },
        "attributeDescriptions": {
            "year": "l'anno del gioco",
            "pop": "la popolazione reale all’inizio dell’anno",
            "seen": "quanti pesci hai visto",
            "want": "quanti pesci volevi catturare",
            "caught": "quanti pesci hai catturato",
            "before": "equilibrio prima del turno",
            "expenses": "spese quest&#39;anno",
            "unitPrice": "prezzo unitario",
            "income": "reddito derivante dalla vendita del pesce",
            "after": "equilibrio dopo il turno",
            "player": "nome del giocatore",
            "game": "codice del gioco",
            "result": "risultato del gioco (quanti pesci hai estratto su 5)",
            "level": "Livello di difficoltà",
            "itemID": "numero identificativo dell&#39;oggetto"
        },
        "mazuFrameTitle": "Mazu, dea del mare",
        "fishFrameTitle": "Gioco di pesca",
        "sAnd": "E",
        "mazuDatasetTitle": "record di gioco",
        "mazuDatasetDescription": "registrazione di tutti i turni dei giocatori",
        "fishDataSetTitle": "registri di pesca",
        "fishDataSetDescription": "registrazioni dell&#39;esperienza della tua barca",
        "fishHistoricalDataSetTitle": "documenti storici",
        "fishHistoricalDataSetDescription": "documenti storici delle barche di tutti",
        "firstPlayer": "Sarai il primo giocatore.",
        "playingSolo": "Stai giocando da solo.",
        "oneOtherPlayer": "C&#39;è un altro giocatore.",
        "manyOtherPlayers": "Ci sono %@1 altri giocatori.",
        "noPlayersYet": "Nessun giocatore ancora!",
        "waitingForYou": "<strong>Ti</strong> aspetto",
        "andHowManyMore": " e %@1 in più.",
        "waitingFor": "Aspettando",
        "catchFishCommand": "Pescare pesci!",
        "end": {
            "timeRanOut": "Il gioco termina nell&#39;anno %@1.<br>",
            "endedEarly": "Il gioco è terminato presto in %@1.<br>",
            "fiveFishResult": "🐟🐟🐟🐟🐟 Bravi! Cinque pesci su cinque!<br> La popolazione ittica totale è sana e così grande che è possibile catturare molti pesci senza ridurre la popolazione ittica. La pesca è oggi una fonte di cibo sostenibile.",
            "fourFishResult": "🐟🐟🐟🐟 Il tuo voto è quattro pesci (su cinque).<br> Il numero totale di pesci è aumentato molto! Ora puoi catturare più pesci senza ridurre la popolazione. Riuscirai ad arrivare a cinque stelle?",
            "threeFishResult": "🐟🐟🐟 Il tuo voto è tre pesci (su cinque).<br> Il numero totale di pesci è aumentato! La tua attività di pesca sta andando bene, ma potrebbe andare meglio.",
            "twoFishResult": "🐟🐟 Il tuo voto è due pesci (su cinque).<br> Il numero totale di pesci è diminuito. La tua attività di pesca è sopravvissuta, ma la popolazione ittica non è sana.",
            "oneFishResult": "🐟 Il tuo voto è solo un pesce (su cinque).<br> Il numero totale di pesci è molto basso. Potresti non essere in grado di continuare a pescare ancora per molto.",
            "zeroFishResult": "💀Il tuo voto  è zero pesci (su cinque)!<br> Presto tutti i pesci scompariranno e l’industria della pesca sarà al collasso.",
            "bankruptFishResult": "💀 Il tuo voto è zero pesci (su cinque)!<br> Hai perso la partita perché questi giocatori sono andati in bancarotta: %@1.",
            "meanBalanceResult": "<br>Alla fine del gioco, il saldo medio era di %@1%@2"
        },
        "everyoneHasFished": "Tutti hanno pescato.",
        "waitingForYouToLogIn": "In attesa che tu acceda",
        "waitForFishSale": "Hai %@1 pesce al mercato del pesce.<br> Aspetta che vengano venduti.",
        "noFishWaitForTurnEnd": "Non hai pesce al mercato del pesce.<br> Aspetta che finisca il turno.",
        "seenFishReport": "Quest&#39;anno hai visto %@1 pesce.",
        "caughtAllReport": "<br>Hai catturato il %@1 pesce che volevi.",
        "caughtSomeReport": "<br>Volevi %@1 pesce, ma ne hai catturati solo %@2.",
        "recentTurnReport": "Il tuo ultimo turno completo è stato l&#39;anno %@1.<br> Hai visto %@2 pesci, volevi %@3 e hai catturato %@4.<br> Li hai venduti per %@7%@5 ciascuno per un totale di %@7%@6.",
        "buttons": {
            "leaveGameButton": "abbandona il gioco",
            "sellFishButton": "vendere pesce",
            "newGameRadioLabel": "nuovo gioco",
            "oldGameRadioLabel": "vecchio gioco"
        },
        "admin": {
            "playerTableHeader": "<tr><th>nome</th><th> vuole</th><th>saldo</th><th> stato</th><th> giocando</th></tr>",
            "fishMarket": "Mercato del Pesce",
            "noGameYet": "non é stato creato ancora un gioco",
            "welcomeBack": "Bentornato",
            "welcomeToMazu": "Benvenuti a Mazu",
            "youHaveRejoined": "Partecipi nuovamente",
            "automateMarket": "automatizzare il mercato"
        },
        "timeTerms": {
            "second": "secondi",
            "minute": "minuti",
            "hour": "ore",
            "day": "giorni",
            "month": "mesi"
        },
        "currencySymbol": "€"
    }
}