mazuStrings.es = {
    "mazu": {
        "fishName": "peces",
        "mazuName": "mazu",
        "language": "español",
        "flags": "🇲🇽,🇪🇸,🇨🇷,🇨🇱",
        "currencySymbol" : "€",

        "staticStrings": {
            "automateCatchLabel": "automatizar? ",
            "playerNameLabelText": "¿cómo se llama? ",
            "fishQuantityLabelText": "¿cuántos peces? ",
            "gameCodeTextFieldLabelText": "código del juego: ",
            "joinGameButton": "unirse",
            "catchButton": "pesque",
            "setNameButton": "Establezca su nombre",
            "loginButton": "ingresar",
            "logoutButton": "cerrar la sesión",
            "tagline": "diosa del mar"
        },
        "attributeNames": {
            "year": "año",
            "pop": "pobl",
            "seen": "visto",
            "want": "desea",
            "caught": "conseguido",
            "before": "antes",
            "expenses": "gastos",
            "unitPrice": "precUnit",
            "income": "ingresos",
            "after": "después",
            "player": "jugador(a)",
            "game": "juego",
            "result": "resultado",
            "level": "nivel",
            "itemID" : "itemID",
        },
        "attributeDescriptions": {
            "year": "año del juego",
            "pop": "población real al principio del año",
            "seen": "cuántos peces vio",
            "want": "cuantos peces quería pescar",
            "caught": "cuantos peces pesquó",
            "before": "saldo antes del turno",
            "expenses": "gastos de este año",
            "unitPrice": "precio unitario",
            "income": "ingresos por la venta de pescado",
            "after": "saldo después del turno",
            "player": "nombre del jugador(a)",
            "game": "código del juego",
            "result": "resultado del juego (cuántos peces ha conseguido de 5)",
            "level": "nivel de dificultad"
        },
        "mazuFrameTitle": "Mazu, Diosa del Mar",
        "fishFrameTitle": "juego de pesca",
        "sAnd": "y",
        "mazuDatasetTitle": "registros de juego",
        "mazuDatasetDescription": "registros de todos los turnos de los jugadores",
        "fishDataSetTitle": "registros de pesca",
        "fishDataSetDescription": "registros de la experiencia de su barco",
        "fishHistoricalDataSetTitle": "registros históricos",
        "fishHistoricalDataSetDescription": "registros históricos de todos los barcos",
        "firstPlayer": "Será el primer jugador",
        "playingSolo": "Está jugando solo",
        "oneOtherPlayer": "Hay un jugador más",
        "manyOtherPlayers": "Hay %@1 otros jugadores",
        "noPlayersYet": "Todavía no hay jugadores",
        "waitingForYou": "Esperando a <strong>Usted</strong>",
        "andHowManyMore": " y %@1 más.",
        "waitingFor": "Esperando a",
        "catchFishCommand": "¡Pesque!",
        "end": {
            "timeRanOut": "El juego termina en el año %@1.<br>",
            "endedEarly": "El juego terminó temprano en %@1. <br>",
            "fiveFishResult": "🐟🐟🐟🐟🐟 ¡Bien hecho! ¡Cinco peces de cinco! \nLa población total de peces es saludable --- y tan grande que se puede pescar mucho sin reducir la población de peces. La pesca es ahora una fuente sostenible de alimentos.",
            "fourFishResult": "🐟🐟🐟🐟 Su puntuación es de cuatro peces (de cinco). <br> ¡El número total de peces ha aumentado mucho! Ahora puedes capturar más peces sin reducir la población. Puedes llegar a las cinco estrellas?",
            "threeFishResult": "🐟🐟🐟 Tu puntuación es de tres peces (de cinco). <br>El número total de peces ha aumentado! Tu negocio de pesca va bien, pero podría ir mejor.",
            "twoFishResult": "🐟🐟 Tu puntuación es de dos peces (de cinco). <br>El número total de peces ha disminuido. Su negocio de pesca ha sobrevivido, pero la población de peces no es saludable.",
            "oneFishResult": "🐟 Tu puntuación es sólo un pez (de cinco). <br>El número total de peces es muy bajo. Es posible que no pueda seguir pescando durante mucho tiempo.",
            "zeroFishResult": "💀  Su puntuación es de cero peces (de cinco)! <br> Los peces pronto desaparecerán y la industria pesquera se ha hundido.",
            "bankruptFishResult": "💀  Su puntuación es de cero peces (de cinco)! <br>Has perdido el juego porque estos jugadores han quebrado: %@1.",
            "meanBalanceResult" : "<br>Al final del juego, el saldo medio era de %@1%@2"
        },
        "everyoneHasFished": "Todos han pescado.",
        "waitingForYouToLogIn": "A la espera de que se conecte",
        "waitForFishSale": "Tiene %@1 peces en la pescadería. <br>Espere a que se vendan.",
        "noFishWaitForTurnEnd": "No tiene pescado en la pescadería. <br>Espere a que termine el turno.",
        "seenFishReport": "Este año, Ud ha visto %@1 peces.",
        "caughtAllReport": "<br>Ha cogido el %@1 de peces que quería.",
        "caughtSomeReport": "<br>Quería %@1 de peces, pero pescó solo %@2.",
        "recentTurnReport": "Su último turno completo fue el año %@1.<br>Vio %@2 peces, quizo %@3 y pescó %@4.<br>Los vendió por $%@5 cada uno para un total de $%@6.",
        "buttons": {
            "leaveGameButton": "salir del juego",
            "sellFishButton": "vender pescado",
            "newGameRadioLabel": "nuevo juego",
            "oldGameRadioLabel": "viejo juego"
        },
        "admin": {
            "playerTableHeader": "<tr>\n                <th>nombre</th>\n                <th>desea</th>\n                <th>saldo</th>\n                <th>estado</th>\n                <th>juega</th>\n</tr>",
            "fishMarket": "Pescadería",
            "noGameYet": "todavía no hay juego",
            "welcomeBack": "Bienvenido de nuevo",
            "welcomeToMazu": "Bienvenido a Mazu",
            "youHaveRejoined": "Ha vuelto a entrar en"
        },
        "timeTerms": {
            "second": "segundos",
            "minute": "minutos",
            "hour": "horas",
            "day": "días",
            "month": "meses"
        }
    }
}